### Section A: Data Structures & Control Structures

#### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
# Creating a list of 5 integers
integer_list = [3, 5, 7, 9, 2]

#Taking a copy of the original list
integer_list_cp = integer_list

print("Integer List: ", integer_list)
print('-'*50)

# append() : which adds an element to the list.
integer_list.append(4)
print('After Appending an element: ', integer_list)
print('-'*50)

# extend() : can add multiple values elements to the list
integer_list.extend([10,11])
print('After Extending elements: ',integer_list)
print('-'*50)

#insert() : Can insert/add elements at particular index
integer_list.insert(3, 0)
print('After Inserting an element: ',integer_list)
print('-'*50)

#remove() : Can remove elements
integer_list.remove(2)
print('After Removing an element: ',integer_list)
print('-'*50)

#pop() : Can delete element
integer_list.pop()
print('After popping an element: ',integer_list)
print('-'*50)

#pop(index) : Can deleting an  element from a aprticular index
element1 = integer_list.pop(2)
print('Element popped out: ',element1)
print('After popping an element at index: ',integer_list)
print('-'*50)


#index(element) : It Return first index of value/element
index_pos = integer_list.index(9)
print('Index position ofthe given element: ',index_pos)
print('-'*50)

#count() :  Return number of occurrences of value.
element_count = integer_list.count(3)
print('Occurance of the given element: ', element_count)
print('-'*50)

#sort(reverse=False) : Sort will arrange the elemnts inside the list in ascending order by default
integer_list.sort()
print('Sorted List in Ascending Order : ',integer_list)
print('-'*50)

#sort() : Sort will arrange the elemnts inside the list in ascending order by default
integer_list_cp.sort(reverse=True)
print('Sorted List in Descending Order : ',integer_list_cp)
print('-'*50)

#remove() : Can remove elements
integer_list.reverse()
print('After Reversing all the elements in the list : ',integer_list)
print('-'*50)

#clear() : Will remove all elements
integer_list.clear()
print('After Removing all elements from the List: ',integer_list)
print('-'*50)

Integer List:  [3, 5, 7, 9, 2]
--------------------------------------------------
After Appending an element:  [3, 5, 7, 9, 2, 4]
--------------------------------------------------
After Extending elements:  [3, 5, 7, 9, 2, 4, 10, 11]
--------------------------------------------------
After Inserting an element:  [3, 5, 7, 0, 9, 2, 4, 10, 11]
--------------------------------------------------
After Removing an element:  [3, 5, 7, 0, 9, 4, 10, 11]
--------------------------------------------------
After popping an element:  [3, 5, 7, 0, 9, 4, 10]
--------------------------------------------------
Element popped out:  7
After popping an element at index:  [3, 5, 0, 9, 4, 10]
--------------------------------------------------
Index position ofthe given element:  3
--------------------------------------------------
Occurance of the given element:  1
--------------------------------------------------
Sorted List in Ascending Order :  [0, 3, 4, 5, 9, 10]
--------------------------------------------------
Sorted List in Descending Order :  [10, 9, 5, 4, 3, 0]
--------------------------------------------------
After Reversing all the elements in the list :  [0, 3, 4, 5, 9, 10]
--------------------------------------------------
After Removing all elements from the List:  []
--------------------------------------------------

#### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [2]:
# Creating a tuple with 3 student names.
student_names = ('Praveen', 'Kiran', 'Sachin')

#Printing the tuple
print(student_names)

#Accessing / Reading the second element from the tuple
print('Second Name: ', student_names[1])

('Praveen', 'Kiran', 'Sachin')
Second Name:  Kiran

In [3]:
#Trying to change the second name with the help of index.
student_names[1]= 'Vinay'

TypeError: 'tuple' object does not support item assignment

In [4]:
'''
 In the above Example we can see that, we are unable to change the tuple value at a particular index, because "tuple" is Immutable in python.
 We can read the data with the help of indexing but we cannot able to write/modify data within the tuple once it is created
'''

'\n In the above Example we can see that, we are unable to change the tuple value at a particular index, because "tuple" is Immutable in python.\n We can read the data with the help of indexing but we cannot able to write/modify data within the tuple once it is created\n'

#### 3.Create a set of integers with some duplicate values. Print the set and explain the output.

##### Set(): In python set is an unordered collection of distinct elements.

In [5]:
# Creating a set:
s1 = {1,2,3,5,7,5,7,8,9}
s1

{1, 2, 3, 5, 7, 8, 9}


#### In Python Set is data type which allows only distinct elements and doesn't allow duplicate elements.
- Set allows Heterogenous data
- Set is Mutable.

#### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary

In [8]:
# Creating a dictionary for a employee data.
employee = {
    'name' : 'Praveen',
    'age' : 32,
    'city' : 'Beijing'
}

# Updating the age of the employee
employee['age'] = 33
print('Employee Details: ',employee)
print('-'*50)

print('Employee details After adding new entry')

# Adding a new entry into the employee data.
employee['email'] = 'amborepraveen@gmail.com'
print('Employee Details: ', employee)

Employee Details:  {'name': 'Praveen', 'age': 33, 'city': 'Beijing'}
--------------------------------------------------
Employee details After adding new entry
Employee Details:  {'name': 'Praveen', 'age': 33, 'city': 'Beijing', 'email': 'amborepraveen@gmail.com'}

#### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [10]:
# Taking Input from the user in the age variable
age = int(input('Enter age to check for voting eligibility of a person: '))

if age >= 18:
    print('Eligibile to vote')
elif age>= 0 and age < 18:
    print('Not Eligible')
else:
    print('Not a valid Input')

Enter age to check for voting eligibility of a person:  23

Eligibile to vote

#### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [12]:
#Taking input from the user in the marks variable
marks = int(input('Enter your marks to check grade: '))

if marks >= 90 and marks <= 100:
    print('A')
elif marks>=75 and marks < 90:
    print('B')
elif marks >= 50 and marks < 75:
    print('C')
elif marks < 50 and marks >=0: 
    print('Fail')
else:
    print('Enter Valid Marks')

Enter your marks to check grade:  22

Fail

#### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [14]:
#Taking number input from the user in the num variable.
num = int(input('Enter a number: '))

#Checking for positive and even number.
if num>0:
    if num %2 == 0:
        print('Positive Even Number')
    else:
        print('Positive Number')
#Checking for zero or negative number
elif num == 0:
        print('Zero')
else:
        print('Negative')

Enter a number:  6

Positive Even Number

### Section B: Numpy

#### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [15]:
import numpy as np

In [16]:

#it creates a 0-dimensional array (scalar array) that just holds the single value 5.
scalar = np.array(5)
print('Scalar: \n',scalar)

#Using.item()
print('Scalar: \n',scalar.item())
print('-'*50)

#1d array with values 1,2,3,4,5
one_dim_array = np.array([1,2,3,4,5])
print('One Dimensional Array: \n', one_dim_array)
print('-'*50)

# 2D array with values: 10,20,30 and 40,50,60 in 2*3 2:rows 3:columns
two_dim_array = np.array([[10, 20, 30], [40,50,60]])
print('Two Dimensiional Array: \n', two_dim_array)

Scalar:
 5
Scalar:
 5
--------------------------------------------------
One Dimensional Array:
 [1 2 3 4 5]
--------------------------------------------------
Two Dimensiional Array:
 [[10 20 30]
 [40 50 60]]

#### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [17]:
import random

In [18]:
# Generating a 4x4 array of random integers between 0 and 100
random_nums_arr = np.random.randint(0,100,size = (4,4))
print(random_nums_arr)

[[86 95 91 74]
 [16 95  4 80]
 [ 4 71 57 40]
 [36 92 73 36]]

In [19]:
lst = np.random.randint(0, 100, 16)
four_x_four = np.array([ lst[:4 ] , lst[4:8] , lst[8:12] , lst[12:16]  ])
print(four_x_four)

[[19 18 44 30]
 [ 6 20 44 98]
 [71  3 87  7]
 [51 35  5 67]]

#### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'

In [20]:
import pandas as pd

In [21]:
# creating a 2D numpy array of shape 3x3 using numpy module and array().
threed_arr = np.array( [[1,2,3],
              [4,5,6],
              [7,8,9]] )
#Converting array into dataframe using pandas module and dataframe.
threed_arr_df = pd.DataFrame(threed_arr, columns = ['A','B','C'])
print(threed_arr_df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

### Section 3:

#### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [22]:
import pandas as pd

In [23]:
# Creating a DataFrame with 10 rows using dictionary.
edata = {
    'Name': ['Ram', 'Shyam', 'Charan', 'Dev', 'isha', 
             'Amit', 'Vinay', 'Ajay', 'Vijay', 'Amit'],  
    'Age': [25, 30, 35, 40, 28, 33, 29, 31, 36, 25],
    'City': ['New York', 'London', 'Paris', 'Berlin', 'Tokyo',
             'Sydney', 'London', 'Paris', 'Berlin', 'New York'],
    'Salary': [50000, 60000, np.nan, 80000, 75000,
               62000, 58000, np.nan, 70000, 50000]
}
#Converting array into dataframe using pandas module and dataframe().
e_df =pd.DataFrame(edata)
print(e_df)

     Name  Age      City   Salary
0     Ram   25  New York  50000.0
1   Shyam   30    London  60000.0
2  Charan   35     Paris      NaN
3     Dev   40    Berlin  80000.0
4    isha   28     Tokyo  75000.0
5    Amit   33    Sydney  62000.0
6   Vinay   29    London  58000.0
7    Ajay   31     Paris      NaN
8   Vijay   36    Berlin  70000.0
9    Amit   25  New York  50000.0

In [24]:
# Using .info(), .describe()
print('-------DataFrame Info-------')
e_df.info()
print('\n-----DataFrame Describe-----')
e_df.describe()

-------DataFrame Info-------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

-----DataFrame Describe-----

             Age        Salary
count  10.000000      8.000000
mean   31.200000  63125.000000
std     4.848826  11051.018053
min    25.000000  50000.000000
25%    28.250000  56000.000000
50%    30.500000  61000.000000
75%    34.500000  71250.000000
max    40.000000  80000.000000

In [25]:
# Selecting 'Name' and 'City' columns
print('\n-----Select Name and City-----')
e_df.loc[: ,['Name', 'City']]

-----Select Name and City-----

     Name      City
0     Ram  New York
1   Shyam    London
2  Charan     Paris
3     Dev    Berlin
4    isha     Tokyo
5    Amit    Sydney
6   Vinay    London
7    Ajay     Paris
8   Vijay    Berlin
9    Amit  New York

In [26]:
# Dropping 'City' column
df_dropped = e_df.drop(columns='City')
print('-----After Dropping City Column-----')
print(df_dropped)

-----After Dropping City Column-----
     Name  Age   Salary
0     Ram   25  50000.0
1   Shyam   30  60000.0
2  Charan   35      NaN
3     Dev   40  80000.0
4    isha   28  75000.0
5    Amit   33  62000.0
6   Vinay   29  58000.0
7    Ajay   31      NaN
8   Vijay   36  70000.0
9    Amit   25  50000.0

In [27]:
# Filling  missing values in 'Salary' column with the mean
e_df['Salary'].fillna(e_df['Salary'].mean())
print("\n----- After Filling Missing Salary -----")
print(e_df)

----- After Filling Missing Salary -----
     Name  Age      City   Salary
0     Ram   25  New York  50000.0
1   Shyam   30    London  60000.0
2  Charan   35     Paris      NaN
3     Dev   40    Berlin  80000.0
4    isha   28     Tokyo  75000.0
5    Amit   33    Sydney  62000.0
6   Vinay   29    London  58000.0
7    Ajay   31     Paris      NaN
8   Vijay   36    Berlin  70000.0
9    Amit   25  New York  50000.0

In [28]:
# Removing duplicate rows
e_df_no_duplicates = e_df.drop_duplicates()
print("\n----- After Removing Duplicates -----")
print(e_df_no_duplicates)

----- After Removing Duplicates -----
     Name  Age      City   Salary
0     Ram   25  New York  50000.0
1   Shyam   30    London  60000.0
2  Charan   35     Paris      NaN
3     Dev   40    Berlin  80000.0
4    isha   28     Tokyo  75000.0
5    Amit   33    Sydney  62000.0
6   Vinay   29    London  58000.0
7    Ajay   31     Paris      NaN
8   Vijay   36    Berlin  70000.0
9    Amit   25  New York  50000.0